[workspace]
members = [
    "air",
    "baby-stark",
    "brakedown",
    "challenger",
    "code",
    "commit",
    "field",
    "fri",
    "goldilocks",
    "keccak",
    "lde",
    "ldt",
    "matrix",
    "merkle-tree",
    "maybe-rayon",
    "mersenne-31",
    "poseidon",
    "symmetric",
    "tensor-pcs",
    "util",
]
