[workspace]
resolver = "2"
members = [
    "air",
    "brakedown",
    "challenger",
    "code",
    "commit",
    "field",
    "fri",
    "goldilocks",
    "keccak",
    "keccak-air",
    "lde",
    "ldt",
    "matrix",
    "merkle-tree",
    "maybe-rayon",
    "mersenne-31",
    "monolith",
    "multi-stark",
    "poseidon",
    "reed-solomon",
    "rescue",
    "symmetric",
    "tensor-pcs",
    "util",
    "uni-stark",
]
