[workspace]
members = [
    "brakedown",
    "challenger",
    "code",
    "commit",
    "field",
    "fri",
    "keccak",
    "ldt",
    "merkle-tree",
    "maybe-rayon",
    "multistark",
    "symmetric",
    "tensor-pcs",
    "util",
]
