[package]
name = "p3-monolith"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-goldilocks = { path = "../goldilocks" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-symmetric = { path = "../symmetric" }
zkhash = { git = "https://extgit.iaik.tugraz.at/krypto/zkfriendlyhashzoo" }
serde = { version = "1.0", features = ["derive"] }