[package]
name = "p3-merkle-tree"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
p3-field = { path = "../field" }
p3-symmetric = { path = "../symmetric" }
p3-commit = { path = "../commit" }
