[package]
name = "p3-rescue"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ethereum-types = "0.14.1"
p3-field = { path = "../field" }
p3-mersenne-31 = { path = "../mersenne-31" }
p3-symmetric = { path = "../symmetric" }
p3-util = { path = "../util" }
rand = "0.8.5"
sha3 = "0.10.8"
