[package]
name = "hyperbrakedown"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hyperfield = { path = "../field" }
hypercode = { path = "../code" }
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "encode"
harness = false
